export enum TunisianState {
  TUNIS = 'Tunis',
  ARIANA = 'Ariana',
  BEN_AROUS = 'Ben Arous',
  MANOUBA = 'Manouba',
  NABEUL = 'Nabeul',
  ZAGHOUAN = 'Zaghouan',
  BIZERTE = 'Bizerte',
  BEJA = 'Beja',
  JENDOUBA = 'Jendouba',
  LE_KAIRAOUAN = 'Kairouan',
  KASSERINE = 'Kasserine',
  SFAX = 'Sfax',
  SIDI_BOUZID = 'Sidi Bouzid',
  SOUSSE = 'Sousse',
  MONASTIR = 'Monastir',
  MAHDIA = 'Mahdia',
  GABES = 'Gabes',
  MEDENINE = 'Medenine',
  TATAOUINE = 'Tataouine',
  TOZEUR = 'Tozeur',
  KEBILI = 'Kebili',
}
